parameters:
  projectName: ''
  workingDirectory: ''

jobs:
- job: StrykerOn${{ parameters.projectName }}
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Install dotnet-stryker'
    inputs:
      command: custom
      custom: tool
      arguments: install dotnet-stryker --tool-path $(Agent.BuildDirectory)/tools --version 0.19.0-alpha.200 --add-source $(MygetFeedUri)
      includeNuGetOrg: true
  - task: Powershell@2
    displayName: Run Stryker on ${{ parameters.projectName }}
    inputs:
      workingDirectory: ${{ parameters.workingDirectory }}
      targetType: 'inline'
      pwsh: true
      ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
        script: $(Agent.BuildDirectory)/tools/dotnet-stryker --reporters "['cleartext', 'html']" --diff --git-source $(Build.SourceBranch) 
      ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
        script: $(Agent.BuildDirectory)/tools/dotnet-stryker --reporters "['cleartext', 'html']" --diff --git-source $(System.PullRequest.TargetBranch)
  - task: PublishMutationReport@0		
    inputs:		
      reportPattern: '${{ parameters.workingDirectory }}/**/mutation-report.html'
