parameters:
  projectName: ''
  workingDirectory: ''

jobs:
- job: StrykerOn${{ parameters.projectName }}
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Install dotnet-stryker'
    inputs:
      command: custom
      custom: tool
      arguments: install dotnet-stryker -g --version 0.18.0-alpha.88 --add-source $(AzureArtifactFeedUri)
      includeNuGetOrg: true
  - task: Powershell@2
    displayName: Run Stryker on ${{ parameters.projectName }}
    inputs:
      workingDirectory: ${{ parameters.workingDirectory }}
      targetType: 'inline'
      pwsh: true
      ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
        script: dotnet stryker --reporters "['dashboard', 'dots', 'html']" --dashboard-api-key $(Stryker.Dashboard.Api.Key) -compare --dashboard-version $(Build.SourceBranchName)
      ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
        script: dotnet stryker --reporters "['dashboard', 'dots', 'html']" --dashboard-api-key $(Stryker.Dashboard.Api.Key) -compare --dashboard-version $(System.PullRequest.SourceBranch) --dashboard-fallback-version $(System.PullRequest.TargetBranch)