parameters:
  projectName: ''
  workingDirectory: ''

jobs:
- job: StrykerOn${{ parameters.projectName }}
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Install dotnet-stryker'
    inputs:
      command: custom
      custom: tool
      arguments: install dotnet-stryker --tool-path $(Agent.BuildDirectory)/tools --version $(IntegrationTestVersion) --add-source $(AzureArtifactFeedUri)
      includeNuGetOrg: false
  - task: Powershell@2
    displayName: Run Stryker on ${{ parameters.projectName }}
    inputs:
      workingDirectory: ${{ parameters.workingDirectory }}
      targetType: 'inline'
      pwsh: true
      ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
        script: $(Agent.BuildDirectory)/tools/dotnet-stryker -l trace --reporters "['dashboard', 'html']" --dashboard-api-key $(Stryker.Dashboard.Api.Key) -compare -bsl Dashboard --dashboard-version $(Build.SourceBranchName) --git-source $(Build.SourceBranchName)
      ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
        script: $(Agent.BuildDirectory)/tools/dotnet-stryker -l trace --reporters "['dashboard', 'html']" --dashboard-api-key $(Stryker.Dashboard.Api.Key) -compare -bsl Dashboard --dashboard-version $(System.PullRequest.SourceBranch) --git-source $(System.PullRequest.TargetBranch)
  - task: PublishMutationReport@0		
    inputs:		
      reportPattern: '${{ parameters.workingDirectory }}/**/mutation-report.html'
