stages:
- stage: UpdatePackageLockFiles
  condition: and(eq(variables['system.pullRequest.isFork'], 'False'), startsWith(variables['system.pullRequest.sourceBranch'], 'renovate'))
  jobs:
  - job: DisableRestoreLockedMode
    steps:
    - script: echo "##vso[task.setvariable variable=RestoreLockedMode]false"
  - job: RestoreAndUpdate
    steps:
    - checkout: self
      persistCredentials: true
    - script: |
        git fetch
        git checkout $(system.pullRequest.sourceBranch)
    - task: UseDotNet@2
      displayName: 'Use dotnet 6'
      inputs:
        version: 6.x
    - task: DotNetCoreCLI@2
      displayName: 'Update stryker cli and stryker core lock files'
      inputs:
        command: 'custom'
        custom: 'restore'
        arguments: --force-evaluate
        workingDirectory: 'src/'
    - task: DotNetCoreCLI@2
      displayName: 'Update integrationtest lock files'
      inputs:
        command: 'custom'
        custom: 'restore'
        arguments: --force-evaluate
        workingDirectory: 'integrationtest/'
    - script: |
        git config --global user.email "renovatebot@stryker-mutator.io"
        git config --global user.name "renovatebot"
        git add -u .
        git commit -m "Update package lock files"
        git push
