stages:
- stage: UpdatePackageLockFiles
  condition: and(eq(variables['system.pullRequest.isFork'], 'False'), startsWith(variables['system.pullRequest.sourceBranch'], 'dependabot'))
  jobs:
  - job: DisableRestoreLockedMode
    steps:
    - script: echo "##vso[task.setvariable variable=RestoreLockedMode]false"
  - job: RestoreAndUpdate
    steps:
    - checkout: self
      persistCredentials: true
    - script: dotnet restore --force-evaluate 'src/Stryker.CLI/Stryker.CLI.sln'
    - script: dotnet restore --force-evaluate 'integrationtest/IntegrationTest.sln'
  - job: CommitAndPush
    steps:
    - script: |
        git config --global user.email "support@dependabot.com"
        git config --global user.name "dependabot"
        git add -u .
        git commit -m "Update package lock files"
        git push origin $(system.pullRequest.sourceBranch)