stages:
- stage: UpdatePackageLockFiles
  condition: and(eq(variables['System.PullRequest.IsFork'], 'False'), startsWith(variables['build.sourcebranch'], 'refs/heads/dependabot'))
  jobs:
  - job: DisableRestoreLockedMode
    steps:
    - script: echo "##vso[task.setvariable variable=RestoreLockedMode]false"
  - job: RestoreAndUpdate
    steps:
    - checkout: self
      persistCredentials: true
    - task: DotNetCoreCLI@2
      displayName: 'Update stryker cli and stryker core lock files'
      inputs:
        command: restore
        arguments: --force-evaluate
        workingDirectory: src/Stryker.CLI
    - task: DotNetCoreCLI@2
      displayName: 'Update integrationtest lock files'
      inputs:
        command: restore
        arguments: --force-evaluate
        workingDirectory: integrationtest
  - job: CommitAndPush
    steps:
    - script: |
        git config --global user.email "support@dependabot.com"
        git config --global user.name "dependabot"
        git add -u .
        git commit -m "Update package lock files"
        git push origin variables['build.sourcebranch']