name: $(PackageVersion).$(VersionBuildNumber)

schedules:
- cron: "0 1 * * *"
  displayName: Nightly
  branches:
    include:
    - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - master
pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - 'docs/*'
    - '.github/*'

variables:
  PackageVersion: '4.16.0'
  VersionBuildNumber: $[counter('4.16.0', 1)]
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
  LibManCacheWindows: $(USERPROFILE)/.librarymanager/cache
  LibManCacheMacLinux: $(HOME)/.librarymanager/cache
  RestoreLockedMode: true

pool:
  vmImage: 'windows-latest'

stages:
- template: pipeline-templates/update-package-lock-files-stage.yml

- stage: Analysis
  dependsOn: UpdatePackageLockFiles
  condition: and(and(not(failed()), not(canceled())), eq(variables['System.PullRequest.IsFork'], 'False'))
  jobs:
  - job:
    displayName: Run Sonar Analysis
    dependsOn: []
    steps:
    - task: UseDotNet@2
      displayName: 'Install dotnet 8'
      inputs:
        version: 8.x
    - task: UseDotNet@2
      displayName: 'Install dotnet 10'
      inputs:
        version: 10.x
    - task: DotNetCoreCLI@2
      displayName: 'Install dotnet-coverage'
      inputs:
        command: custom
        custom: tool
        arguments: install dotnet-coverage --tool-path $(Agent.BuildDirectory)/tools
        includeNuGetOrg: true
    - template: pipeline-templates/populate-cache-steps.yml
    - task: SonarCloudPrepare@4
      inputs:
        SonarCloud: 'SonarCloud stryker-net'
        organization: 'stryker-net'
        scannerMode: 'dotnet'
        projectKey: 'stryker-net'
        projectName: 'Stryker .NET'
        projectVersion: '$(PackageVersion)'
        extraProperties: |
          sonar.verbose=true
          sonar.cs.vscoveragexml.reportsPaths=$(Agent.BuildDirectory)\TestResults\coverage.xml
    - task: DotNetCoreCLI@2
      displayName: 'Build Stryker'
      inputs:
        command: 'build'
        projects: 'src/Stryker.slnx'
    - pwsh: '$(Agent.BuildDirectory)/tools/dotnet-coverage collect "dotnet test" -f xml -o "$(Agent.BuildDirectory)\TestResults\coverage.xml"'
      displayName: 'Run unit tests'
      workingDirectory: 'src'
    - task: SonarCloudAnalyze@4
    - task: SonarCloudPublish@4
      inputs:
        pollingTimeoutSec: '300'

- stage: PublishMasterReleaseArtifact
  displayName: Publish Release Artifact
  dependsOn: Analysis
  condition: and(and(not(failed()), not(canceled())), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: PublishRelease
    displayName: Publish Release Artifacts
    steps:
    - template: pipeline-templates/populate-cache-steps.yml
    - task: UseDotNet@2
      displayName: 'Use dotnet'
      inputs:
        version: 8.x
    - task: UseDotNet@2
      displayName: 'Use dotnet'
      inputs:
        version: 10.x
    - task: DotNetCoreCLI@2
      displayName: 'Pack Stryker.CLI'
      inputs:
        command: custom
        custom: pack
        arguments: --output $(Build.ArtifactStagingDirectory)/release
        workingDirectory: 'src/Stryker.CLI/Stryker.CLI'
    - task: DotNetCoreCLI@2
      displayName: 'Pack Stryker.Core'
      inputs:
        command: custom
        custom: pack
        arguments: --output $(Build.ArtifactStagingDirectory)/release
        workingDirectory: 'src/Stryker.Core/Stryker.Core'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: release'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/release'
        ArtifactName: release
