using System.Collections.Generic;
using System.IO;
using System.IO.Abstractions.TestingHelpers;
using System.Linq;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Shouldly;
using Stryker.Configuration.Options;
using Stryker.Core.Initialisation;
using Stryker.Core.ProjectComponents.Csharp;
using Stryker.Core.ProjectComponents.SourceProjects;

namespace Stryker.Core.UnitTest.Initialisation;

[TestClass]
public class CsharpProjectComponentsBuilderTests : TestBase
{
    private const string ProjectDir = @"C:\ExampleProject";
    private const string ProjectFilePath = @"C:\ExampleProject\ExampleProject.csproj";

    private static StrykerOptions DefaultOptions => new();

    private static CsharpProjectComponentsBuilder CreateBuilder(
        MockFileSystem fileSystem,
        string[] sourceFiles,
        Dictionary<string, string> extraProperties = null)
    {
        var properties = new Dictionary<string, string>
        {
            { "IsTestProject", "False" },
            { "Language", "C#" },
            { "TargetDir", Path.Combine(ProjectDir, "bin", "Debug", "net8.0") },
            { "TargetFileName", "ExampleProject.dll" },
            { "AssemblyName", "ExampleProject" },
        };

        if (extraProperties != null)
        {
            foreach (var (key, value) in extraProperties)
            {
                properties[key] = value;
            }
        }

        var analyzerResultMock = TestHelper.SetupProjectAnalyzerResult(
            properties: properties,
            projectFilePath: ProjectFilePath,
            sourceFiles: sourceFiles,
            preprocessorSymbols: ["NET8_0"]);

        var projectInfo = new SourceProjectInfo
        {
            AnalyzerResult = analyzerResultMock.Object,
        };

        return new CsharpProjectComponentsBuilder(
            projectInfo,
            DefaultOptions,
            [],
            NullLogger.Instance,
            fileSystem);
    }

    [TestMethod]
    public void Build_ShouldInclude_RegularCsFiles_InMutatedFiles()
    {
        var regularFile = Path.Combine(ProjectDir, "MyClass.cs");
        var fileSystem = new MockFileSystem(new Dictionary<string, MockFileData>
        {
            { ProjectFilePath, new MockFileData("<Project/>") },
            { regularFile, new MockFileData("public class MyClass { }") },
        });

        var builder = CreateBuilder(fileSystem, [regularFile]);

        var result = (CsharpFolderComposite)builder.Build();

        result.GetAllFiles().Select(f => f.FullPath).ShouldContain(regularFile);
    }

    [TestMethod]
    public void Build_ShouldNotMutate_ButShouldAddToCompilationSyntaxTrees_DesignerCsFiles()
    {
        var designerFile = Path.Combine(ProjectDir, "Form1.designer.cs");
        var fileSystem = new MockFileSystem(new Dictionary<string, MockFileData>
        {
            { ProjectFilePath, new MockFileData("<Project/>") },
            { designerFile, new MockFileData("public class Form1 { }") },
        });

        var builder = CreateBuilder(fileSystem, [designerFile]);

        var result = (CsharpFolderComposite)builder.Build();

        // designer.cs files are generated: not in mutated files, but added to compilation trees
        result.GetAllFiles().Select(f => f.FullPath).ShouldNotContain(designerFile);
        result.CompilationSyntaxTrees.Where(t => t != null).Select(t => t.FilePath).ShouldContain(designerFile);
    }

    [TestMethod]
    public void Build_ShouldSkipEntirely_SourceGeneratorOutputFiles_DotGDotCs()
    {
        // A *.razor.g.cs file produced by the Blazor Razor source generator.
        // It must be skipped entirely - not added to mutated files NOR to compilationSyntaxTrees,
        // because the source generator will regenerate it during compilation.
        var razorGeneratedFile = Path.Combine(ProjectDir, "obj", "Debug", "net8.0", "Counter.razor.g.cs");
        const string autoGenContent =
            """
            // <auto-generated/>
            #pragma warning disable 1591
            namespace BlazorApp { public partial class Counter { } }
            """;
        var regularFile = Path.Combine(ProjectDir, "MyClass.cs");
        var fileSystem = new MockFileSystem(new Dictionary<string, MockFileData>
        {
            { ProjectFilePath, new MockFileData("<Project/>") },
            { razorGeneratedFile, new MockFileData(autoGenContent) },
            { regularFile, new MockFileData("public class MyClass { }") },
        });

        var builder = CreateBuilder(fileSystem, [razorGeneratedFile, regularFile]);

        var result = (CsharpFolderComposite)builder.Build();

        // The razor.g.cs file must not appear in either collection
        result.GetAllFiles().Select(f => f.FullPath).ShouldNotContain(razorGeneratedFile);
        result.CompilationSyntaxTrees.Where(t => t != null).Select(t => t.FilePath).ShouldNotContain(razorGeneratedFile);

        // The regular file should still be present for mutation
        result.GetAllFiles().Select(f => f.FullPath).ShouldContain(regularFile);
    }

    [TestMethod]
    public void Build_ShouldSkipEntirely_SourceGeneratorOutputFiles_SimpleGDotCs()
    {
        // A simple *.g.cs file (not razor-specific) is also source-generator output
        var generatedFile = Path.Combine(ProjectDir, "obj", "Debug", "net8.0", "Generated.g.cs");
        const string autoGenContent =
            """
            // <auto-generated/>
            namespace Generated { public class Foo { } }
            """;
        var fileSystem = new MockFileSystem(new Dictionary<string, MockFileData>
        {
            { ProjectFilePath, new MockFileData("<Project/>") },
            { generatedFile, new MockFileData(autoGenContent) },
        });

        var builder = CreateBuilder(fileSystem, [generatedFile]);

        var result = (CsharpFolderComposite)builder.Build();

        result.GetAllFiles().ShouldBeEmpty();
        result.CompilationSyntaxTrees.Where(t => t != null).ShouldBeEmpty();
    }

    [TestMethod]
    public void Build_ShouldNotSkip_DesignerFiles_FromCompilationTrees_EvenWithAutoGeneratedComment()
    {
        // A *.designer.cs file is generated/static code – it's NOT a source-generator output.
        // It should still be added to compilationSyntaxTrees so the project compiles correctly.
        var designerFile = Path.Combine(ProjectDir, "Resources.designer.cs");
        const string content =
            """
            // <auto-generated/>
            namespace App { public class Resources { } }
            """;
        var fileSystem = new MockFileSystem(new Dictionary<string, MockFileData>
        {
            { ProjectFilePath, new MockFileData("<Project/>") },
            { designerFile, new MockFileData(content) },
        });

        var builder = CreateBuilder(fileSystem, [designerFile]);

        var result = (CsharpFolderComposite)builder.Build();

        result.GetAllFiles().ShouldBeEmpty();
        result.CompilationSyntaxTrees.Where(t => t != null).Select(t => t.FilePath).ShouldContain(designerFile);
    }

    [TestMethod]
    public void Build_ShouldHandleMixedFiles_RegularAndSourceGeneratorOutput()
    {
        var regularFile1 = Path.Combine(ProjectDir, "ClassA.cs");
        var regularFile2 = Path.Combine(ProjectDir, "ClassB.cs");
        var razorGen1 = Path.Combine(ProjectDir, "obj", "Counter.razor.g.cs");
        var razorGen2 = Path.Combine(ProjectDir, "obj", "Index.razor.g.cs");
        var designer = Path.Combine(ProjectDir, "Settings.designer.cs");

        const string autoGenContent = "// <auto-generated/>\npublic class X { }";

        var fileSystem = new MockFileSystem(new Dictionary<string, MockFileData>
        {
            { ProjectFilePath, new MockFileData("<Project/>") },
            { regularFile1, new MockFileData("public class ClassA { }") },
            { regularFile2, new MockFileData("public class ClassB { }") },
            { razorGen1, new MockFileData(autoGenContent) },
            { razorGen2, new MockFileData(autoGenContent) },
            { designer, new MockFileData("public class Settings { }") },
        });

        var builder = CreateBuilder(fileSystem, [regularFile1, regularFile2, razorGen1, razorGen2, designer]);

        var result = (CsharpFolderComposite)builder.Build();

        var allFilePaths = result.GetAllFiles().Select(f => f.FullPath).ToList();
        var compilationTreePaths = result.CompilationSyntaxTrees.Where(t => t != null).Select(t => t.FilePath).ToList();

        // Regular files are mutated
        allFilePaths.ShouldContain(regularFile1);
        allFilePaths.ShouldContain(regularFile2);

        // Source-generator outputs are skipped entirely
        allFilePaths.ShouldNotContain(razorGen1);
        allFilePaths.ShouldNotContain(razorGen2);
        compilationTreePaths.ShouldNotContain(razorGen1);
        compilationTreePaths.ShouldNotContain(razorGen2);

        // Designer file is in compilation trees but not mutated
        allFilePaths.ShouldNotContain(designer);
        compilationTreePaths.ShouldContain(designer);
    }
}
