<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Assets\Tests\Editor\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.6.1" />
    <ProjectReference Include="UnityEditor.TestRunner.csproj" />
    <ProjectReference Include="UnityEngine.TestRunner.csproj" />
    <ProjectReference Include="UnityProject.csproj" />
  </ItemGroup>
</Project>
