version: 1

update_configs:
- package_manager: "dotnet:nuget"
  directory: "/src/Stryker.CLI"
  update_schedule: "live"
  target_branch: "master"
  automerged_updates:
  - match:
      dependency_type: "all"
      update_type: "semver:minor"
- package_manager: "dotnet:nuget"
  directory: "/src/Stryker.Core/Stryker.Core/ToolHelpers"
  update_schedule: "live"
  target_branch: "master"
  automerged_updates:
  - match:
      dependency_type: "all"
      update_type: "semver:minor"
- package_manager: "dotnet:nuget"
  directory: "/integrationtest"
  update_schedule: "live"
  target_branch: "master"
  automerged_updates:
  - match:
      dependency_type: "all"
      update_type: "semver:minor"
- package_manager: "dotnet:nuget"
  directory: "/integrationtest/TargetProjects/NetFramework"
  update_schedule: "live"
  target_branch: "master"
  automerged_updates:
  - match:
      dependency_type: "all"
      update_type: "semver:minor"
