name: 'Lint PR'

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  main:
    name: Validate PR title
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    permissions:
      pull-requests: read
    steps:
        # see https://github.com/marketplace/actions/semantic-pull-request for configuration options
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (newline-delimited).
          types: |
            [fF]eat
            [fF]ix
            [dD]ocs
            [sS]tyle
            [rR]efactor
            [tT]est
            [cC]hore
          # Configure that a scope must always be provided.
          requireScope: true
